#!/usr/bin/env bash

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t "$1"
    else
        tmux switch-client -t "$1"
    fi
}

has_session() {
    tmux list-sessions | grep -q "^$1:"
}

hydrate() {
    if [[ -f "$2/.tmux-sessionizer" ]]; then
        tmux send-keys -t "$1" "source \"$2/.tmux-sessionizer\"" C-m
    elif [[ -f "$HOME/.tmux-sessionizer" ]]; then
        tmux send-keys -t "$1" "source \"$HOME/.tmux-sessionizer\"" C-m
    fi
}

if [[ $# -eq 1 ]]; then
    selected="$1"
else
    selected=$(find ~/Documents ~/kaas ~/kaas/env ~/Projects -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

# Sanitize session name: replace spaces and dots with underscores
selected_name=$(basename "$selected" | tr ' .:' '_')
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -ds "$selected_name" -c "$selected"
    hydrate "$selected_name" "$selected"
fi

if ! has_session "$selected_name"; then
    tmux new-session -ds "$selected_name" -c "$selected"
    hydrate "$selected_name" "$selected"
fi

switch_to "$selected_name"
